baseURL: "https://scottmacleod.co"
languageCode: "en-au"
title: "Scott MacLeod"
theme: "hugo-tania"
paginate: 6

params:
  titleEmoji: "🚀"

menu:
  footer:
    - name: RSS
      url: "/index.xml"

markup:
  highlight:
    noClasses: false
    lineNos: true
  goldmark:
    renderer:
    unsafe: true
