baseURL = "https://scottmacleod.co"
title = "Scott MacLeod"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "hugo-paper"

[[params.mainMenu]]
    link = "/posts"
    text = "writing"

[[params.mainMenu]]
    link = "/reading-list"
    text = "things to read"


[[params.mainMenu]]
    link = "/about"
    text = "who dis?"
